[package]
name = "qop"
version = "0.0.0"
authors = ["cchexcode <alexanderh.weber@outlook.com>"]
edition = "2024"
license = "MIT"
description = "A simple and powerful database migration tool."
homepage = "https://github.com/cchexcode/qop"
repository = "https://github.com/cchexcode/qop"
keywords = ["database", "migration", "sql", "postgres", "cli"]
categories = ["command-line-utilities", "database"]
readme = "docs/README.md"

[features]
default = []

[dependencies]
tokio = { version = "1.46.1", features = [
    "rt",
    "rt-multi-thread",
    "macros",
    "process",
    "io-util",
    "time",
    "sync",
] }
clap = "4.5.41"
clap_complete = "4.5.55"
clap_mangen = "0.2.28"
clap-markdown = "0.1.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
bytes = "1.10.1"
crossterm = "0.29.0"
anyhow = "1.0.98"
signal-hook = "0.3.18"
parking_lot = "0.12.4"
chrono = { version = "0.4.41", features = ["serde"] }
toml = "0.9.2"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres", "chrono"]}
comfy-table = "7.1.1"
path-clean = "1.0.1"
sqlparser = "0.49"
pep440_rs = "0.7"

[dev-dependencies]
hoox = "0.3.0"
