[package]
name = "qop"
version = "0.0.0"
authors = ["cchexcode <alexanderh.weber@outlook.com>"]
edition = "2024"
license = "MIT"
description = "A more powerful alternative to Makefiles."
homepage = "https://github.com/cchexcode/qop"
repository = "https://github.com/cchexcode/qop"
keywords = ["make", "cli", "task", "runner"]
categories = ["command-line-utilities"]
readme = "docs/README.md"

[features]
default = []

[dependencies]
tokio = { version = "1.43.0", features = [
    "rt",
    "rt-multi-thread",
    "macros",
    "process",
    "io-util",
    "time",
    "sync",
] }
clap = "4.5.29"
clap_complete = "4.5.44"
clap_mangen = "0.2.26"
clap-markdown = "0.1.4"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
bytes = "1.10.0"
crossterm = "0.28.1"
anyhow = "1.0.95"
signal-hook = "0.3.17"
parking_lot = "0.12.3"
chrono = { version = "0.4.39", features = ["serde"] }
toml = "0.9.2"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres", "chrono"]}
comfy-table = "7.1.1"

[dev-dependencies]
hoox = "0.3.0"
